baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Docs'
theme = 'docs'

[module]
    [[module.imports]]
        path = "github.com/gtsteffaniak/filebrowserDocsTheme"
        disable = false
